# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: windows-2019

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '14.x'

- script: |
    which node > node.txt
    set /p nodepath= < node.txt
    mkdir nodejs
    cp "%nodepath%" nodejs/node.exe
    rm node.txt    
  displayName: 'Copy node.exe to target'

- task: DownloadSecureFile@1
  displayName: 'Download secure file'
  inputs:
    secureFile: 'text-image-service.production.env'
    retryCount: 

- task: CopyFiles@2
  displayName: 'Copy .env file'
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: '*.production.env'
    TargetFolder: .

- task: KirKone.fileoperations.rename.rename@0
  displayName: 'rename: text-image-service.production.env'
  inputs:
    SourceFile: 'text-image-service.production.env'
    NewName: .env.production

- task: Npm@0
  displayName: 'npm install'
  inputs:
    arguments: '--force --production=false'

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'

- task: DeleteFiles@1
  displayName: 'Delete build files'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
     **/node-sass/build/*
     **/.git/*

- task: ArchiveFiles@1
  displayName: 'Archive files'
  inputs:
    rootFolder: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: tar
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).tar.gz'

- task: CopyFiles@2
  displayName: 'Copy File to: $(TargetFolder)'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '$(Build.BuildId).tar.gz'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\ArtifactsToBePublished'